# Generated by Django 5.0.4 on 2024-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_status_order_updated_at_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='item_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
