# Generated by Django 5.0.4 on 2024-06-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_orderdetail_item_name_orderdetail_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('APPROVED', 'Order Approved'), ('SHIPPED', 'Order Shipped'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], default='PLACED', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.order'),
        ),
    ]
