# Generated by Django 5.0.4 on 2024-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='itemname',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
