# Generated by Django 5.0.4 on 2024-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_food_items_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
    ]
